### ISSUE TITLE
V11 Error

### ISSUE THREAD

**Issue by uniwars** [spetzel2020/quick-encounters#136] opened 2023-07-11 12:34 UTC
Hi, with v11 and last module update I get this error in the module setup page :

The module "quick-encounters" is using "name" which is deprecated in favor of "id"

**Comment by spetzel2020** [comment] 2023-07-11 13:15
Thanks for the report. Is this preventing installation or just a
deprecation warning?

**Comment by spetzel2020** [comment] 2023-07-11 23:00
It is definitely true that Quick Encounters is still using the `name` field and I believe at some point I did see the deprecation warning that you mention.

However I have just done both an upgrade (from 1.1.5 to 1.1.6) and then an uninstall and reinstall, and in neither case do I see the message described. Can you help by saying whether it's an Error, Warning or otherwise?

**Comment by uniwars** [comment] 2023-07-11 23:05
sorry for the delay, it's a warning in the add-on module setup page, sorry for the confusion

**Comment by spetzel2020** [comment] 2023-07-11 23:26
> sorry for the delay, it's a warning in the add-on module setup page, sorry for the confusion

- No problem. Is it preventing installation? (hopefully not if it's a warning).
- What version of Foundry are you running?
- If possible it would be great if you could uninstall/reinstall QE and send me a screenshot. I have been unable to reproduce and am not getting any direction from asking in the dev channel.

**Comment by uniwars** [comment] 2023-07-12 09:57
it doesn't prevent installation
![image](https://github.com/spetzel2020/quick-encounters/assets/65986545/0962b6d8-52f9-4701-97d6-21b846615faf)
V11 last stable 305

**Comment by spetzel2020** [comment] 2023-09-13 02:11
Moving this to Milestone 1.3 for fixing deprecation warnings in v11. Hopefully can add `id` as an additional tag so that it will work in v9-v11.

**Comment by spetzel2020** [comment] 2024-06-17 15:22
Plan to add `id` as additional tag with Foundry v10-v12 support

**Comment by spetzel2020** [comment] 2024-06-18 00:20
Added in 12.1.0c (not yet released)

**Comment by spetzel2020** [comment] 2024-06-19 02:46
Released in 12.0.1; waiting on admin tool update.

**Comment by spetzel2020** [comment] 2024-06-21 17:27
Released in 12.1.1

**Closed by spetzel2020** 2024-06-21 17:27 UTC
