### ISSUE TITLE
Tokens spawning with 50% opacity

### ISSUE THREAD

**Issue by ScootyMcBoogerBalls** [spetzel2020/quick-encounters#125] opened 2023-01-23 15:06 UTC
Hi,

I was trying to find a way to easily fill taverns with random commoners.

So I set up Wildcards for the commoner and selected random names with Token mold.

And it works fine. When I drag and drop them one by one.

But if I use Quick Encounters and simply put in 1d10+5 Commoners.

And click on Run QE, with Ctrl (because I don't want them invisible).

They all spawn with 50% opacity.

How to get them to spawn normally?

**Comment by spetzel2020** [comment] 2023-01-23 15:19
That's weird. I'll take a look. Can you open an Issue wuth essentially this
information? That way you'll get informed of developments.

**Comment by ClownCoach** [comment] 2023-03-05 15:34
I also have this bug, seems to only occur when trying to run a QE with Compendium linked actors. if I used imported actors they don't have any issues with opacity. Damn shame because its a good feature. Hoping it gets patched soon.

**Comment by spetzel2020** [comment] 2023-03-28 23:56
I am getting this problem with generated tokens (as opposed to captured ones), regardless of Compendium or not.

**Comment by spetzel2020** [comment] 2023-03-29 00:20
in `QuickEncounter.js#generateFullExtractorActorTokenData()#1342`, we call:
` tempTokenData = await actor.getTokenDocument(tokenData);`
On `foundry.js#16492`:
`return new cls(tokenData, {actor: this});` changes `alpha` to `0.5` from `1`.

**Comment by spetzel2020** [comment] 2023-03-29 22:52
The Foundry code is behaving as designed, by "helping" the GM see hidden tokens as `alpha=0.5`. Unfortunately this means that to make them look right, you have to change `alpha=0.5` to ` in the settings menu of each token.

None of the above explains why Compendium actors **always** apparently have `alpha=0.5` even for visible.
Researching that now.

**Comment by spetzel2020** [comment] 2023-03-29 23:26
Ok, resolved this - all related to using the wrong `tokenData` saved for creating tokens. This was also creating hidden tokens that did not automatically change to `alpha=1` when made visible.

**Comment by spetzel2020** [comment] 2023-04-05 04:28
Released in 1.1.3

**Closed by spetzel2020** 2023-04-05 04:28 UTC
Labels: bug, fixed
