### ISSUE TITLE
Issue adding tiles to quick encounter

### ISSUE THREAD

**Issue by mjoreilly1986** [spetzel2020/quick-encounters#79] opened 2022-02-03 08:10 UTC
I have tried adding multiple variations of tiles and none will work on running a QE. Static images and animated do not show whether they are classes as foreground or background. Errors change between line 936 and 941 depending if it is a foreground tile or background tile. 

![Capture](https://user-images.githubusercontent.com/50317988/152304344-253a025a-0d09-4889-8b40-881984eae438.JPG)

![cap2](https://user-images.githubusercontent.com/50317988/152304560-49d5936d-adab-4016-847c-e0717e8e5586.JPG)

Line 1239 "const createdTiles = await Tile.create(duplicate(shiftedTilesData));" Is coming up with the error with the initial error.

Also lines 936 and 941. I can’t get any tile to work with quick encounters. All three lines in the code are coming back with the error. Doesn’t matter if it is a foreground or background tile

Version 9 Build 249.

**Comment by spetzel2020** [comment] 2022-02-03 17:43
Reproduced in 9.245. Looks like old code that somehow crept back into this version.

**Comment by spetzel2020** [comment] 2022-02-03 18:35
I believe I have fixed this in 0.9.9#QuickEncounter.js . I will do more extensive testing later on , but in the meantime you could try it out by copying `https://github.com/spetzel2020/quick-encounters/blob/0.9-maintenance/modules/QuickEncounter.js`
over the existing file in your Foundry installation (under your data directory, in `modules/quick-encounters`.

Note the `0.9-maintenance`; this is not on `master` but on a maintenance branch.

**Comment by spetzel2020** [comment] 2022-02-04 16:58
Released in [0.9.9](https://github.com/spetzel2020/quick-encounters/releases/tag/v0.9.9)

**Closed by spetzel2020** 2022-02-04 16:58 UTC
Labels: bug
